---
Files:
  ATOK: ATOK.bin
  SPAM: SpamCount.bin
Tower1:
  IP: "192.168.0.50"
  ESP0: ATOK
  ESP1: SPAM
  ESP2: ATOK
  ESP3: SPAM
  ESP4: ATOK
  ESP5: SPAM
  ESP6: ATOK
  ESP7: SPAM
  ESP8: ATOK
  ESP9: SPAM
  ESP10: ATOK
  ESP11: SPAM
  ESP12: ATOK
  ESP13: SPAM
  ESP14: ATOK
Tower2:
  IP: "192.168.0.51"
  ESP0: ATOK
  ESP1: SPAM
  ESP2: ATOK
  ESP3: SPAM
  ESP4: ATOK
  ESP5: SPAM
  ESP6: ATOK
  ESP7: SPAM
  ESP8: ATOK
  ESP9: SPAM
  ESP10: ATOK
  ESP11: SPAM
  ESP12: ATOK
  ESP13: SPAM
  ESP14: ATOK
Tower3: ~
Tower4: ~
Tower5: ~
